version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - POSTGRES_PW=root
    depends_on:
      - db

volumes:
  db-data: